Product.create(name: "Planet Globula terrarium", description: "Handmade terrarium", image_url: "terrarium.JPG", price: 10.0)
Product.create(name: "Planet Globula notepad", description: "Handmade notepad with stone paper and himalayan paper cover. Various sizes", image_url: "notepad.JPG", price: 5.0)
Product.create(name: "Planet Globula terrarium kit", description: "Handmade terrarium kit with instructions", image_url: "kit.jpg", price: 100.0)
Product.create(name: "Acrylic painting", description: "Acrylic painting on Hahnemühle paper 50x65cm", image_url: "pgpainting.JPG", price: 100.0)
Product.create(name: "Planet Globula notepad", description: "Handmade notepad with papyrus paper cover.", image_url: "papirus.JPG", price: 5.0)
Product.create(name: "Acrylic painting", description: "Acrylic painting on Hahnemühle paper 50x65cm", image_url: "framed2.JPG", price: 100.0)
Order.create(user_id: 1, product_id: 1, total: 10.0)
Order.create(user_id: 1, product_id: 2, total: 5.0)
